Repository matomo-org/tag-manager, pull requests merged in 2018-07, with the labels that each got.

#20 Add Facebook Pixel Tag Type to Matomo Tag Manager
  Template/Tag/FacebookPixelTag.php
  Template/Tag/FacebookPixelTag.web.js
  images/icons/F_icon.svg
Labels: New Tag

#37 Ensure ignore zero string value when set as limit
  Model/Tag.php
  Model/Trigger.php
  Model/Variable.php
  Template/Trigger/FullscreenTrigger.web.js
  Template/Trigger/TimerTrigger.web.js
  Template/Trigger/WindowLeaveTrigger.web.js
  angularjs/manageVariable/edit.controller.js
  angularjs/manageVariable/model.js
  tests/UI/expected-screenshots/ContainerTag_tag_none_exist_yet_create_now.png
Labels: Bug

#35 improve wording
  lang/en.json
  tests/Integration/Model/EnvironmentTest.php
  tests/Integration/SystemSettingTest.php
Labels: not-in-changelog

#39 Support assigning object values in Custom HTML tag
  CHANGELOG.md
  LEGALNOTICE
  Template/Tag/CustomHtmlTag.php
  Template/Tag/CustomHtmlTag.web.js
  javascripts/tagmanager.js
  javascripts/tagmanager.min.js
  stylesheets/manageEdit.less
  tests/Integration/Context/BaseContext/TemplateLocatorTest.php
  tests/Integration/Model/TagTest.php
  tests/Integration/ReleaseCheckListTest.php
  tests/System/expected/context_webcontext_generate.text
  tests/System/expected/test_tag1__TagManager.getContainerTag.xml
  tests/System/expected/test_tag2__TagManager.getContainerTag.xml
  tests/System/expected/test_webContext__TagManager.getAvailableTagTypesInContext.xml
  tests/System/expected/test_with_content__TagManager.getContainerTags.xml
  tests/UI/expected-screenshots/ContainerTag_create_advanced_blocktrigger_created.png
  tests/UI/expected-screenshots/ContainerTag_create_advanced_firetrigger_created.png
  tests/UI/expected-screenshots/ContainerTag_create_advanced_firetrigger_error.png
  tests/UI/expected-screenshots/ContainerTag_create_advanced_prefilled1.png
  tests/UI/expected-screenshots/ContainerTag_create_advanced_prefilled2.png
  tests/UI/expected-screenshots/ContainerTag_create_advanced_submitted.png
  tests/UI/expected-screenshots/ContainerTag_create_new_error.png
  tests/UI/expected-screenshots/ContainerTag_create_new_prefilled.png
  tests/UI/expected-screenshots/ContainerTag_create_new_submitted.png
  tests/UI/expected-screenshots/ContainerTag_create_new_type_selected.png
  tests/UI/expected-screenshots/ContainerTag_edit_through_list.png
  tests/UI/expected-screenshots/ContainerTag_edit_trigger_directly_popup.png
  tests/UI/expected-screenshots/ContainerTag_edit_trigger_directly_updated.png
  tests/UI/expected-screenshots/ContainerTag_edit_url.png
  tests/UI/expected-screenshots/ContainerTag_edit_url_updated.png
  tests/javascript/index.php
Labels: Enhancement

#42 Using lookup for matchValue
  Context/BaseContext.php
Labels: Needs Review

#44 ConstantVariable copy should use a temp variable
  javascripts/tagmanager.js
  javascripts/tagmanager.min.js
Labels: Bug
