Repository matomo-org/tag-manager, pull requests merged in 2018-12, with the labels that each got.

#124 Tag Manager out of beta
  README.md
Labels: Needs Review

#135 Trigger activity only if that api was called directly
  Activity/BaseActivity.php
  Activity/TagAdded.php
  Activity/TagDeleted.php
  Activity/TagUpdated.php
  Activity/TriggerAdded.php
  Activity/TriggerDeleted.php
  Activity/TriggerUpdated.php
  Activity/VariableAdded.php
  Activity/VariableDeleted.php
  Activity/VariableUpdated.php
Labels: Bug

#136 Ensure matomo idSite can be assigned a variable
  Template/Variable/MatomoConfigurationVariable.php
  tests/System/expected/test_webContext__TagManager.getAvailableVariableTypesInContext.xml
Labels: not-in-changelog

#137 Make sure super user can edit custom templates when only allowing super user
  TagManager.php
Labels: Bug

#99 Etracker event
  Template/Tag/EtrackerTag.php
  Template/Tag/EtrackerTag.web.js
  Template/Variable/EtrackerConfigurationVariable.php
  Template/Variable/EtrackerConfigurationVariable.web.js
  images/icons/etracker.svg
  lang/en.json
Labels: Needs Review, New Tag

#123 Support custom title and url for pageviews
  Template/Tag/MatomoTag.php
  Template/Tag/MatomoTag.web.js
Labels: Needs Review, not-in-changelog

#139 Convert fire_delay to int so tests pass on mysqli
  Dao/TagsDao.php
  tests/System/expected/context_androidcontext_generate.text
  tests/System/expected/context_ioscontext_generate.text
  tests/System/expected/context_webcontext_generate.text
Labels: not-in-changelog

#142 The tag manager debug screen should not require 2FA
  TagManager.php
Labels: not-in-changelog
