Repository matomo-org/tag-manager, pull requests merged in 2018-09, with the labels that each got.

#73 Link to Manage Tags page in top menu when user has only view access
  CHANGELOG.md
  Menu.php
  plugin.json
Labels: Bug

#75 fix filename of HoneybadgerTag
  Template/Tag/HoneybadgerTag.web.js
Labels: not-in-changelog

#84 Update button disabled if you remove a condition from a trigger
  angularjs/manageTrigger/edit.controller.js
Labels: not-in-changelog

#83 Add support for Click Element Match CSS Selector
  Model/Comparison.php
  Template/Trigger/AllDownloadsClickTrigger.web.js
  Template/Trigger/AllElementsClickTrigger.web.js
  Template/Trigger/AllLinksClickTrigger.web.js
  Template/Variable/PreConfigured/ClickElement.php
  javascripts/tagmanager.js
  javascripts/tagmanager.min.js
  lang/en.json
  tests/System/expected/test___TagManager.getAvailableComparisons.xml
  tests/System/expected/test_no_content__TagManager.getAvailableContainerVariables.xml
  tests/System/expected/test_with_content__TagManager.getAvailableContainerVariables.xml
  tests/UI/expected-screenshots/ContainerVariable_variable_some_exist.png
  tests/javascript/index.php
Labels: not-in-changelog

#55 add bugsnag tag
  Template/Tag/BugsnagTag.php
  Template/Tag/BugsnagTag.web.js
  images/icons/bugsnag.png
  lang/en.json
Labels: Needs Review, New Tag

#85 Support form element
  Template/Trigger/FormSubmitTrigger.web.js
  Template/Variable/PreConfigured/FormElement.php
  lang/en.json
  tests/System/expected/test_no_content__TagManager.getAvailableContainerVariables.xml
  tests/System/expected/test_with_content__TagManager.getAvailableContainerVariables.xml
  tests/UI/expected-screenshots/ContainerVariable_variable_some_exist.png
  tests/javascript/index.php
Labels: not-in-changelog
