Repository matomo-org/tag-manager, pull requests merged in 2020-06, with the labels that each got.

#250 Fix Using variable in Matomo URL results in validation error
  Template/Variable/MatomoConfigurationVariable.php
Labels: not-in-changelog

#251 Ensure a date and period is set even if $_POST might be empty
  Context/WebContext/JavaScriptTagManagerLoader.php
Labels: Needs Review

#219 Umlauts destroy variables in same string
  Context/BaseContext.php
  tests/System/ContextTest.php
Labels: Needs Review

#210 When publishing a new version, and the version name is auto generated…
  angularjs/manageVersion/edit.controller.js
Labels: Enhancement

#215 Fix form destination name
  Template/Variable/PreConfigured/FormDestinationVariable.php
  lang/en.json
  tests/System/expected/test_no_content__TagManager.getAvailableContainerVariables.xml
  tests/System/expected/test_with_content__TagManager.getAvailableContainerVariables.xml
Labels: Needs Review, not-in-changelog

#231 Unsanitize tag name in preview mode
  Context/WebContext.php
Labels: Needs Review, not-in-changelog

#254 Fix materializecss modal options
  javascripts/tagmanagerHelper.js
Labels: Needs Review, not-in-changelog
