Repository matomo-org/tag-manager, pull requests merged in 2024-03, with the labels that each got.

#766 Add 'require consent for campaigns tracking' setting
  Template/Tag/MatomoTag.web.js
  Template/Variable/MatomoConfigurationVariable.php
  lang/en.json
  tests/System/expected/test___TagManager.exportContainerVersion_site_default_container.xml
  tests/System/expected/test_webContext__TagManager.getAvailableVariableTypesInContext.xml
Labels: Enhancement, Needs Review

#774 Add variable migration to update existing tags
  Updates/5.1.0-b1.php
Labels: c: Privacy, Needs Review

#770 Added code to remove All websites from site selector dropdown, #PG-3196
  templates/manageContainers.twig
  templates/tagmanager.twig
  tests/UI/Container_spec.js
  tests/UI/TagManager_spec.js
  tests/UI/expected-screenshots/Container_websites_dropdown_without_all_websites.png
  tests/UI/expected-screenshots/TagManager_websites_dropdown_without_all_websites.png
Labels: Needs Review
